### ISSUE TITLE
Failed to calculate a perceptual hash over 1024 files

### ISSUE THREAD

**Issue by b1n4ryj4n** [appleappleapplenanner/hydrus-video-deduplicator#9]
Now the only error that still occurs for every file after > ~1000 files:
`Failed to calculate a perceptual hash`

**Comment by b1n4ryj4n** [comment]
Now i know from where it comes:

`Error [Errno 24] Too many open files`

somewhere the files wont get closed after calculating the hash

**Comment by appleappleapplenanner** [comment]
Good catch. Seems to be caused by the call to the vpdq extension to hash the video.

I'll just clean up all zombie processes every chunk to fix this.

Let me know if newest version fixes it.

**Comment by b1n4ryj4n** [comment]
Hm the zombie processes are gone but I still get the error 'To many open files' after ~1000 files.

**Comment by appleappleapplenanner** [comment]
I see. The file descriptor count is definitely going up. Seems to be from vpdq.computeHash. I thought it was from something with the tempfile but I'm pretty sure it's not.

I'll fork vpdq and see if I can fix it.

**Comment by appleappleapplenanner** [comment]
Should be fixed in the newest version. Only issue you might have is errors while getting the new forked package, `hvdvpdq`. If you do just try `pip uninstall vpdq`.

**Comment by b1n4ryj4n** [comment]
Very good job! Now it seams to work 😎
